

const FETCH_POSTS_REQUEST="FETCH_POSTS_REQUEST";
const FETCH_POSTS_SUCCESS="FETCH_POSTS_SUCCESS";
const FETCH_POSTS_ERROR="FETCH_POSTS_ERROR";
const FETCH_POST_REQUEST="FETCH_POST_REQUEST";
const FETCH_POST_SUCCESS="FETCH_POST_SUCCESS";
const FETCH_POST_ERROR="FETCH_POST_ERROR";